env: CartPole
# model-config: model_configs/cont_latent.yaml
# model-config: model_configs/feed_forward.yaml
model-config: model_configs/feed_forward_fov.yaml

output: /data/domain_adaptation/experiments/cartpole/

# train with action noise
train-dataset-location: /data/varyingsim/datasets/cartpole_relabeled_train.pickle
test-datasets: [/data/varyingsim/datasets/cartpole_relabeled_test.pickle]
test-names: [test-ribbon]

dataset-type: RelabeledEpisodicFovDataset
name: cartpole
group: cartpole_relabel_1
seed: 2
device: cuda

epochs: 30
test-iter: 100

obs-skip: 50

batch-size: 64
lr: 1e-3
context-size: 8
num-workers: 8

lr-step-size: 15
lr-gamma: 0.1
optim: adam
