seed: 0
suffix: "single_"
same_act: False
rand_reset: True
same_state: False
num_train_episodes: 1000
num_train_actions: 10
num_test_episodes: 100
num_test_actions: 10
action_std: 0.05
min_vel: 0.1
max_vel: 0.3
test_type: all
fov_format: proportion
fov_params:
  puck_mass:
    low: 0.275
    high: 0.275
    prop_train: 0.9
    n_stripes: 4
  # puck_size:
  #   low: 0.01
  #   high: 0.04
  #   prop_train: 0.9
  #   n_stripes: 4
  friction:
    low: 0.06
    high: 0.06
    prop_train: 0.9
    n_stripes: 4
  pusher_friction:
    low: 0.06
    high: 0.6
    prop_train: 0.9
    n_stripes: 4
  wind_x:
    low: 0
    high: 0
    prop_train: 0.9
    n_stripes: 4
  wind_y:
    low: 0
    high: 0
    prop_train: 0.9
    n_stripes: 4
  table_tilt_x:
    low: 0
    high: 0
    prop_train: 0.9
    n_stripes: 4
  table_tilt_y:
    low: 0
    high: 0
    prop_train: 0.9
    n_stripes: 4
  damping:
    low: 0.03755
    high: 0.03755
    prop_train: 0.9
    n_stripes: 4

  