env: PushBoxOffset
model-config: model_configs/transformer_latent.yaml

output: /data/domain_adaptation/experiments/push_box/
train-dataset-location: /data/varyingsim/datasets/push_box_K_100_R_2000_seed_0_train.pickle
val-dataset-location: /data/varyingsim/datasets/push_box_K_20_R_100_seed_0_val.pickle
test-datasets: [/data/varyingsim/datasets/push_box_K_20_R_100_seed_0_test.pickle]
test-names: [test]

dataset-type: EpisodicStartEndFovDataset
name: pushbox_transformer
group: pushbox_obs
seed: 0
device: cuda

use-obs-fn: true

epochs: 151
test-iter: 75
save-iter: 5000

obs-skip: 50

batch-size: 64
lr: 1e-3
context-size: 8

lr-step-size: 15000
lr-gamma: 0.1
optim: adam
no-wandb: true