env: DummyEnv
env-nu: 2
env-nq: 2
env-nv: 0

model-config: model_configs/feed_forward.yaml

output: /data/domain_adaptation/experiments/sliding/baseline

# train with action noise
train-dataset-location: /data/sliding/one_train/
test-datasets: [/data/sliding/test/]
test-names: [test]

dataset-type: RobotPushDataset
name: sliding_single_more
group: sliding
seed: 1
device: cuda

project: domain_adaptation_icra
# project: robot_domain_adaptation


epochs: 70000
test-iter: 100
save-iter: 2500

batch-size: 64
lr: 1e-3
context-size: 4

lr-step-size: 2000
lr-gamma: 0.1
optim: adam

# load-model-location: /data/domain_adaptation/experiments/push_box/baseline/proto_unsupervised-2021-04-29_23-25-26/
# model-name: model.pickle
# freeze-encoder: True