env: PushBoxOffset
model-config: model_configs/feed_forward.yaml

output: /vast/bne215/data/varyingsim/experiments/push_box/
train-dataset-location: /vast/bne215/data/varyingsim/datasets/push_box_K_100_R_2000_seed_2_train.pickle
val-dataset-location: /vast/bne215/data/varyingsim/datasets/push_box_K_20_R_100_seed_2_val.pickle
test-datasets: [/vast/bne215/data/varyingsim/datasets/push_box_K_20_R_100_seed_2_test.pickle]
test-names: [test]

dataset-type: EpisodicStartEndFovDataset
name: pushbox_ff
group: pushbox_obs
seed: 2
device: cuda

use-obs-fn: true

epochs: 20000
test-iter: 250
save-iter: 5000

obs-skip: 50

batch-size: 64
lr: 1e-3
context-size: 8

lr-step-size: 15000
lr-gamma: 0.1
optim: adam