name: varyingsim
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip:
    - aim>=2.0.0
    - torch>=1.5.0
    - mujoco-py<2.1,>=2.0
    - gym>=0.15.0
    - numpy>=1.15.0
    - configargparse
    - pyyaml

